# Generated by Django 4.1.7 on 2023-02-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zerg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attack', models.PositiveIntegerField()),
                ('defence', models.PositiveIntegerField()),
                ('speed', models.PositiveIntegerField()),
                ('health', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
