# Generated by Django 4.1.7 on 2023-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_rename_zerg_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='gas_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='mineral_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
