# Generated by Django 4.1.7 on 2023-02-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_unit_capacity_unit_gas_cost_unit_mineral_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='attack',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='unit',
            name='defence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit',
            name='health',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='speed',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
