# Generated by Django 4.1.7 on 2023-02-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_unit_anti_air'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='race',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='units.race'),
        ),
    ]
