# Generated by Django 4.1.7 on 2023-02-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_race_unit_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
