# Generated by Django 4.1.7 on 2023-02-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_unit_flying_unit_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='anti_air',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='defence',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='description',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='flying_unit',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='gas_cost',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='health',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='mineral_cost',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='race',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='speed',
        ),
        migrations.AddField(
            model_name='worker',
            name='unit_ptr',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='worker', serialize=False, to='units.unit'),
        ),
    ]
