# Generated by Django 4.1.7 on 2023-02-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_remove_worker_anti_air_remove_worker_attack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='unit_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='worker', serialize=False, to='units.unit'),
        ),
    ]
